"""Add is_approved field to user_tours table

Revision ID: 314e7732437a
Revises: ac9296a0781c
Create Date: 2023-11-13 16:35:16.211229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314e7732437a'
down_revision = 'ac9296a0781c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tours', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
