"""removed is_approved field to user_tours table

Revision ID: 35126d7553de
Revises: 314e7732437a
Create Date: 2023-11-13 21:42:05.973849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35126d7553de'
down_revision = '314e7732437a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tours', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
